language: python

python:
  - 3.8

git:
  depth: false
 
dist: bionic

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry --version

install:
  - poetry install -v
  - poetry show -v

before_script:
  - prospector --version
  - black --version
  - isort --version

script:
  - prospector
  - black ./ --check --verbose
  - isort ./ --recursive --check-only --verbose

before_deploy:
  - portray as_html -ov
  - chmod -R 777 ci

deploy:
  - provider: script
    script: bash ci/deploy_pypi.sh
    skip-cleanup: true
    on:
      tags: true

  - provider: pages
    edge: true
    github_token: $GITHUB_TOKEN
    local_dir: "site"
    committer_from_gh: true
    on:
      branch: master

notifications:
  email: false