language: python

python:
  - 3.7

git:
  depth: false
 
dist: bionic

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry --version

install:
  - poetry update -v
  - poetry show -v

before_script:
  - pytest --version
  - prospector --version
  - black --version
  - isort --version

script: 
  - pytest -v
  - prospector
  - black ./ --check --verbose
  - isort ./ --recursive --check-only --verbose

before_deploy:
  - portray as_html -ov

deploy:
  - provider: pages
    edge: true
    github_token: $GITHUB_TOKEN
    local_dir: "site"
    committer_from_gh: true
    on:
      branch: master

notifications:
  email: false