name: Deploy to pypi

on:
  push:
    tags: "v*"

jobs:
  publish_pypi:
    name: Publish to pypi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish --username=__token__ --password="$PYPI_TOKEN" --build

  publish_release_note:
    name: Publish release note
    runs-on: ubuntu-latest
    needs: publish_pypi

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --current --strip header
        env:
          OUTPUT: CHANGELOG.md
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ steps.git-cliff.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
