name: Deploy github pages

on:
  push:
    branches:
      - master

jobs:

  deploy_page:
    name: Deploy Github page
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: |
          poetry install
      - name: Activate virtualenv
        run: |
          source .venv/bin/activate
      - name: Build Page
        run: |
          portray as_html -ov
      - name: Deploy GitHub Page
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
