name: Check python application

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: |
          poetry install
      - name: Run nox
        run: |
          source .venv/bin/activate
          nox
